In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent_list = ['How are you?', 'My name is Vansh', 'I like coffee' , 'Go to the gym coward', 'the glass of milk', 'the glass of juice', 'she is very beautiful']

In [3]:
# vocabulary size
voc_size =10000

In [4]:
# one hot representation

one_hot_repr = [ one_hot(words, voc_size) for words in sent_list]
one_hot_repr

[[7780, 1580, 776],
 [4468, 5953, 1834, 7159],
 [4842, 2322, 9852],
 [2331, 1590, 263, 4059, 8534],
 [263, 5470, 1684, 1950],
 [263, 5470, 1684, 9343],
 [4767, 1834, 5827, 7759]]

In [5]:
# word embedding representation

from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

In [6]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0    0 7780 1580  776]
 [   0    0    0    0 4468 5953 1834 7159]
 [   0    0    0    0    0 4842 2322 9852]
 [   0    0    0 2331 1590  263 4059 8534]
 [   0    0    0    0  263 5470 1684 1950]
 [   0    0    0    0  263 5470 1684 9343]
 [   0    0    0    0 4767 1834 5827 7759]]


In [7]:
# feature representation

dim = 10

In [12]:
model = Sequential()

# Add embedding layer
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_len))

# Compile the model
model.compile(optimizer='adam', loss='mse')

c:\Users\DELL\OneDrive\Desktop\rnn\env\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 446ms/step


array([[[ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.252717

In [15]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0,    0, 7780, 1580,  776], dtype=int32)

In [23]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step


array([[[ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.25271727e-02,
         -2.94910073e-02],
        [ 3.21699120e-02,  4.81630825e-02, -8.38889927e-03,
          4.12740745e-02, -2.52389312e-02,  1.00956336e-02,
          4.21988852e-02, -2.30728630e-02,  4.252717